version: "3.7"

services:
  app:
    build: .
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NODE_PORT: 3000
    env_file:
      - ./src/config/index.js
